p8105\_hw6\_nc2710
================
Nicole Comfort
11/25/2018

Problem 1
---------

The Washington Post has gathered data on homicides in 50 large U.S. cities and made the data available through a GitHub repository. The code below loads the raw data (which we also saw on the previous homework):

``` r
homicide_data = read_csv(file = "./data/homicide-data.csv") # import dataset
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

The raw data is a dataframe regarding homicides from 28 different states that took place from Jan 1, 2007 to November 2015. The dataset is composed of 52179 observations of 12 variables. The variables include: unique case ID, reported date, victim last name and first name, as well as demographic information of the victim (race, age, sex). There is also information on the location including city, state, latitude/longitude, and finally, the disposition of the case (e.g. whether or not the case was resolved).

The code chunk below creates a city\_state variable (e.g. “Baltimore, MD”) and a binary variable indicating whether the homicide is solved. We also omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. We omit Tulsa, AL – this is a data entry mistake. The code modifies victim\_race to have categories white and non-white, with white as the reference category. We also further omitted cases where the race was coded as "Unknown". Lastly, we ensure sure that victim\_age is numeric.

``` r
homicide_data = 
  homicide_data %>% 
  janitor::clean_names() %>% # clean names
  mutate(city_state = str_c(city, state, sep = ", ", collapse = NULL)) %>% # create a city_state variable
  filter(city_state != "Tulsa, AL") %>% 
  filter(city_state != "Dallas, TX") %>% 
  filter(city_state != "Phoenix, AZ") %>% 
  filter(city_state != "Kansas City, MO") %>% # omit certain cities
  mutate(is_solved = recode(disposition,    # create binary variable for whether case is solved
                       "Closed without arrest" = FALSE,
                       "Open/No arrest" = FALSE,
                       "Closed by arrest" = TRUE)) %>% 
  mutate(is_solved = as.numeric(is_solved)) %>% # 1 is for solved cases, 0 for unsolved 
  mutate(is_solved = as.factor(is_solved)) %>%  # not sure if this conversion is necessary
  mutate(victim_age = as.numeric(victim_age)) %>% # make victim age numeric
  filter(victim_race != "Unknown") %>% # remove cases where race is unknown 
  mutate(victim_race = str_replace(victim_race, "Hispanic", "Non-White"),
         victim_race = str_replace(victim_race, "Other", "Non-White"),
         victim_race = str_replace(victim_race, "Black", "Non-White"),
         victim_race = str_replace(victim_race, "Asian", "Non-White"), 
         victim_race = as_factor(victim_race),
         victim_race = fct_relevel(victim_race, "White", "Non-White"),
         victim_sex = factor(victim_sex))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

``` r
         # Above modifies the victim_race variable to have categories White and Non-White with White as the reference category
         # We removed the cases where the victim_race was coded as "Unknown" 
```

For the city of Baltimore, MD, we use the glm function to fit a logistic regression with resolved (Note: coded as is\_solved = 1) vs unresolved (coded as is\_solved = 0) as the outcome and victim age, sex, and race (white/non-white) as predictors.

The output of the glm is saved as an R object, `glm_baltimore`; we apply the broom::tidy to this object and obtain the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing non-white victims to white victims, keeping all other variables fixed.

``` r
baltimore_df =   # examine city of Baltimore, MD only 
  homicide_data %>% 
  filter(city_state == "Baltimore, MD")

glm_baltimore = 
  baltimore_df %>% 
  glm(is_solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) # save output of glm as R object

# apply broom::tidy to this object 
  broom::tidy(glm_baltimore, conf.int = TRUE) %>% 
  mutate(OR = exp(estimate),
         conf_lower = exp(conf.low),
         conf_upper = exp(conf.high)) %>% 
  select(term, log_OR = estimate, OR, conf_lower, conf_upper, p.value) %>% # also need to obtain the confidence interval of the OR
  filter(term == "victim_raceNon-White") %>% 
  knitr::kable(digits = 3)
```

| term                  |  log\_OR|     OR|  conf\_lower|  conf\_upper|  p.value|
|:----------------------|--------:|------:|------------:|------------:|--------:|
| victim\_raceNon-White |    -0.82|  0.441|        0.312|         0.62|        0|

``` r
print(glm_baltimore)
```

    ## 
    ## Call:  glm(formula = is_solved ~ victim_age + victim_sex + victim_race, 
    ##     family = binomial(), data = .)
    ## 
    ## Coefficients:
    ##          (Intercept)            victim_age        victim_sexMale  
    ##              1.18603              -0.00699              -0.88779  
    ## victim_raceNon-White  
    ##             -0.81960  
    ## 
    ## Degrees of Freedom: 2826 Total (i.e. Null);  2823 Residual
    ## Null Deviance:       3676 
    ## Residual Deviance: 3597  AIC: 3605

From the results of the logistic regression, we can see that the odds ratio for a homicide being resolved comparing non-whites to whites (all other variables fixed) is 0.441. In other words, the odds of a homicide being resolved are 55.9% lower for non-whites compared to whites, adjusting for the victim's age, sex, and race. We are 95% confident that the true odds ratio for resolved homicides comparing non-whites to whites, keeping other variables constant, lies within the range (0.312, 0.62).

Next, I will run a glm for each of the cities in my dataset, and will extract the adjusted odds ratio (and CI) for solving homicides comparing non-white victims to white victims. *Do this within a “tidy” pipeline, making use of purrr::map, list columns, and unnest as necessary to create a dataframe with estimated ORs and CIs for each city.*

``` r
homicide_data = 
  homicide_data %>% 
  mutate(is_solved = recode(is_solved,
                            "0" = "unresolved",
                            "1" = "resolved")) # got an error so need to recode 
                                               # note that I'm still comparing resolved cases to unresolved, i.e. unresolved is the ref category

nest_glm_all <-
  homicide_data %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(models = map(data, ~glm(is_solved ~ victim_age + victim_race + victim_sex,
                                 data = .,
                                 family = binomial())),
         models = map(models, broom::tidy, conf.int = TRUE)) %>% 
  select(-data) %>% 
  unnest()
# code SHOULD work but I'm getting error: glm.fit: fitted probabilities numerically 0 or 1 occurred 
```

From these resuts, I will create a dataframe that includes the adjusted ORs and CIs (for solved homicide cases, comparing non-whites to whites) for each city.

``` r
all_city_OR <-
  nest_glm_all %>% 
    mutate(OR = exp(estimate),
           conf_lower = exp(conf.low),
           conf_upper = exp(conf.high)) %>%
    dplyr::select(city_state, term, OR, conf_lower, conf_upper) %>%
    filter(term == "victim_raceNon-white")  
```

I display the results in a table below:

``` r
all_city_OR %>%
   knitr::kable(digits = 3)
```

Lastly, I create a plot that shows the estimated ORs and CIs for each city. Cities are organized according to the estimated OR.

``` r
# need to edit 
all_city_OR %>%
  mutate(city_state = forcats::fct_reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y = OR)) + 
      geom_errorbar(aes(ymin = conf_lower, ymax = conf_upper), width = 0.2) +
      geom_point(size = 3, shape = 21, fill = "white") + 
  labs(
    title = "Solved homicides, comparing non-white victims to white victims",
    x = "City",
    y = "Adjusted odds ratio",
    caption = "Data from the Washington Post, adjusted for victim age, race, and sex"
  ) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
```

DISCUSS/comment on the plot.

Problem 2
---------

In this problem, I will analyze data gathered to understand the effects of several variables on a child’s birthweight. This dataset consists of 4,342 children and includes the following variables:

-   babysex: baby’s sex (male = 1, female = 2)

-   bhead: baby’s head circumference at birth (centimeters)

-   blength: baby’s length at birth (centimeteres)

-   bwt: baby’s birth weight (grams)

-   delwt: mother’s weight at delivery (pounds)

-   fincome: family monthly income (in hundreds, rounded)

-   frace: father’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other, 9 = Unknown)

-   gaweeks: gestational age in weeks

-   malform: presence of malformations that could affect weight (0 = absent, 1 = present)

-   menarche: mother’s age at menarche (years)

-   mheight: mother’s height (inches)

-   momage: mother’s age at delivery (years)

-   mrace: mother’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other)

-   parity: number of live births prior to this pregnancy

-   pnumlbw: previous number of low birth weight babies

-   pnumgsa: number of prior small for gestational age babies

-   ppbmi: mother’s pre-pregnancy BMI

-   ppwt: mother’s pre-pregnancy weight (pounds)

-   smoken: average number of cigarettes smoked per day during pregnancy

-   wtgain: mother’s weight gain during pregnancy (pounds)

The code below loads and clean the data for regression analysis (i.e. converts numeric to factor where appropriate, checks for missing data, etc.).

``` r
# Import data
birthweight_data = read_csv(file = "./data/birthweight.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_integer(),
    ##   gaweeks = col_double(),
    ##   ppbmi = col_double(),
    ##   smoken = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
# Manipulate data
birthweight_data = 
  birthweight_data %>% 
  mutate(
      babysex = factor(babysex),
      frace = factor(frace),
      malform = factor(malform),
      mrace = factor(mrace)
  )

# Check missing data
birthweight_data %>% 
  is.na() %>% summary()
```

    ##   babysex          bhead          blength           bwt         
    ##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
    ##  FALSE:4342      FALSE:4342      FALSE:4342      FALSE:4342     
    ##    delwt          fincome          frace          gaweeks       
    ##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
    ##  FALSE:4342      FALSE:4342      FALSE:4342      FALSE:4342     
    ##   malform         menarche        mheight          momage       
    ##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
    ##  FALSE:4342      FALSE:4342      FALSE:4342      FALSE:4342     
    ##    mrace           parity         pnumlbw         pnumsga       
    ##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
    ##  FALSE:4342      FALSE:4342      FALSE:4342      FALSE:4342     
    ##    ppbmi            ppwt           smoken          wtgain       
    ##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
    ##  FALSE:4342      FALSE:4342      FALSE:4342      FALSE:4342

There is no missing data.

### Proposed regression model for birthweight

Socioeconomic status, whether assessed by income, education, or occupation, is linked to a wide range of health problems. Thus, I propose to run a linear regression model based on a hypothesized structure, i.e. a model that investigates the relationship between birthweight and socioeconomic status (estimated by family monthly income), adjusted for other factors that, according to the literature, may contribute to low birthweight.

Those covariates are: mother's weight at delivery, gestational age in weeks, presence of malformations, previous number of low birthweight babies, smoking status, and mother's pre-pregnancy BMI. (I will also perform a sensitity analysis that includes maternal height and pre-pregnancy weight to see if these are more informative than BMI.)

First, I look at the relationship between birthweight and family income in a simple, unadjusted linear regression (univariate analysis).

``` r
# Look at whether family income predicts birthweight, univariate analysis
simple_model = 
  lm(bwt ~ fincome, data = birthweight_data) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

print(simple_model)
```

    ## 
    ## 
    ## term           estimate   std.error   statistic   p.value
    ## ------------  ---------  ----------  ----------  --------
    ## (Intercept)    2979.987      15.135     196.897         0
    ## fincome           3.048       0.296      10.307         0

In a simple, unadjusted linear regression model, family monthly income (continuous variable) is a significant predictor of birthweight, such that birthweight increases with increasing family monthly income.

We will next see if this relationship holds when adjusting for covariates:

``` r
# Look at whether family income predicts birthweight, adjusted for covariates 
adjusted_model =
  lm(bwt ~ fincome + delwt + gaweeks + malform + pnumlbw + smoken + ppbmi, data = birthweight_data) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 4)

print(adjusted_model)
```

    ## 
    ## 
    ## term           estimate   std.error   statistic   p.value
    ## ------------  ---------  ----------  ----------  --------
    ## (Intercept)    104.6347     94.0439      1.1126    0.2659
    ## fincome          2.1257      0.2591      8.2035    0.0000
    ## delwt            8.7211      0.4391     19.8636    0.0000
    ## gaweeks         58.9204      2.1482     27.4284    0.0000
    ## malform1        27.8465    113.6258      0.2451    0.8064
    ## smoken          -7.9068      0.9044     -8.7426    0.0000
    ## ppbmi          -29.8499      3.0387     -9.8234    0.0000

``` r
# sensitivity analyses 
lm(bwt ~ fincome + delwt + gaweeks + malform + pnumlbw + smoken + ppbmi + mheight,
   data = birthweight_data) %>% 
  broom::tidy()
```

    ## # A tibble: 8 x 5
    ##   term        estimate std.error statistic   p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
    ## 1 (Intercept)   389.     241.        1.61  1.06e-  1
    ## 2 fincome         2.16     0.261     8.30  1.40e- 16
    ## 3 delwt           9.27     0.615    15.1   3.71e- 50
    ## 4 gaweeks        58.7      2.15     27.3   2.68e-151
    ## 5 malform1       23.7    114.        0.208 8.35e-  1
    ## 6 smoken         -7.88     0.904    -8.72  4.02e- 18
    ## 7 ppbmi         -33.0      3.91     -8.45  4.01e- 17
    ## 8 mheight        -4.58     3.57     -1.28  2.00e-  1

``` r
lm(bwt ~ fincome + delwt + gaweeks + malform + pnumlbw + smoken + ppbmi + mheight + ppwt,
   data = birthweight_data) %>% 
  broom::tidy()
```

    ## # A tibble: 9 x 5
    ##   term        estimate std.error statistic   p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
    ## 1 (Intercept) -3001.    1052.       -2.85  4.36e-  3
    ## 2 fincome         2.14     0.261     8.23  2.53e- 16
    ## 3 delwt           9.56     0.620    15.4   2.94e- 52
    ## 4 gaweeks        58.6      2.15     27.2   1.06e-150
    ## 5 malform1       24.2    114.        0.213 8.31e-  1
    ## 6 smoken         -7.85     0.904    -8.69  4.94e- 18
    ## 7 ppbmi          44.9     23.9       1.88  5.99e-  2
    ## 8 mheight        48.7     16.5       2.95  3.16e-  3
    ## 9 ppwt          -13.9      4.19     -3.31  9.44e-  4

Even after adjusting for mother's weight at delivery, gestational age in weeks, presence of congenital malformations, having given birth to previous low birthweight babies, smoking, and mother's pre-pregnancy BMI, family monthly income is still significantly associated with birthweight, such that for each increase in a unit of family monthly income ($100), birthweight increases by 2.13 grams (p = 3.05e-16).

In a sensitivity analysis that also included maternal height as a predictor and maternal height + pre-pregnancy weight, the estimated coefficient for family income essentially did not change. Thus, using pre-pregnancy BMI was sufficient.

Next, I review the model fit statistics of my simple and adjusted model. I also noticed that there are very few cases of malformations at birth, so try taking that out of the model and review the model fit statistics.

``` r
# review fit statistics 
lm(bwt ~ fincome, data = birthweight_data) %>% 
  broom::glance()
```

    ## # A tibble: 1 x 11
    ##   r.squared adj.r.squared sigma statistic  p.value    df  logLik    AIC
    ## *     <dbl>         <dbl> <dbl>     <dbl>    <dbl> <int>   <dbl>  <dbl>
    ## 1    0.0239        0.0237  506.      106. 1.26e-24     2 -33196. 66398.
    ## # ... with 3 more variables: BIC <dbl>, deviance <dbl>, df.residual <int>

``` r
lm(bwt ~ fincome + delwt + gaweeks + malform + pnumlbw + smoken + ppbmi, data = birthweight_data) %>% 
  broom::glance()
```

    ## # A tibble: 1 x 11
    ##   r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC
    ## *     <dbl>         <dbl> <dbl>     <dbl>     <dbl> <int>   <dbl>  <dbl>
    ## 1     0.266         0.265  439.      262. 4.69e-287     7 -32576. 65168.
    ## # ... with 3 more variables: BIC <dbl>, deviance <dbl>, df.residual <int>

``` r
lm(bwt ~ fincome + delwt + gaweeks+ pnumlbw + smoken + ppbmi, data = birthweight_data) %>% 
  broom::glance()
```

    ## # A tibble: 1 x 11
    ##   r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC
    ## *     <dbl>         <dbl> <dbl>     <dbl>     <dbl> <int>   <dbl>  <dbl>
    ## 1     0.266         0.265  439.      315. 2.59e-288     6 -32576. 65167.
    ## # ... with 3 more variables: BIC <dbl>, deviance <dbl>, df.residual <int>

``` r
# final model selection
final_model = lm(bwt ~ fincome + delwt + gaweeks+ pnumlbw + smoken + ppbmi, data = birthweight_data)
```

Removing malformations as a covariate does not change the R squared or adjusted R squared and slightly reduces the AIC, so I will use the adjusted model that excludes malformations:

`lm(bwt ~ fincome + delwt + gaweeks+ pnumlbw + smoken + ppbmi, data = birthweight_data)`.

Next, I examine a plot of the model's residuals against the fitted values.

``` r
# plot model residuals against fitted values - use add_predictions and add_residuals in making this plot
model_resid =
  modelr::add_residuals(birthweight_data, final_model)
```

    ## Warning in predict.lm(model, data): prediction from a rank-deficient fit
    ## may be misleading

``` r
model_pred =
  modelr::add_predictions(birthweight_data, final_model)
```

    ## Warning in predict.lm(model, data): prediction from a rank-deficient fit
    ## may be misleading

``` r
plot_df =
  birthweight_data %>% 
    mutate(resid = model_resid$resid,
           pred = model_pred$pred)
  
plot_df %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "Proposed model residuals vs fitted values",
    x = "Predicted value",
    y = "Residuals",
    caption = "Model: lm(bwt ~ fincome + delwt + gaweeks+ pnumlbw + smoken + ppbmi, data = birthweight_data)"
  )
```

    ## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'

<img src="p8105_hw6_nc2710_files/figure-markdown_github/residuals plot-1.png" width="95%" />

From the regression diagnostics, we can see that this model obviously needs some work. While the residuals generally look centered around zero, there is a trend where the residuals decrease as the predicted value increases. This model may include too many covariates/be over-fitting.

*Note: Model building itself is not a main idea of the course and this model therefore is by no means "optimal"*

I will next compare my model to two others:

-   One using length at birth and gestational age as predictors (main effects only)
-   One using head circumference, length, sex, and all interactions (including the three-way interaction) between these

I run these models below:

``` r
# include length at birth and gestational age as predictors (main effects)
model_one_fit =
  lm(bwt ~ blength + gaweeks, data = birthweight_data) 

model_one_fit %>% broom::tidy()
```

    ## # A tibble: 3 x 5
    ##   term        estimate std.error statistic  p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
    ## 1 (Intercept)  -4348.      98.0      -44.4 0.      
    ## 2 blength        129.       1.99      64.6 0.      
    ## 3 gaweeks         27.0      1.72      15.7 2.36e-54

``` r
model_one_fit %>% broom::glance()
```

    ## # A tibble: 1 x 11
    ##   r.squared adj.r.squared sigma statistic p.value    df  logLik    AIC
    ## *     <dbl>         <dbl> <dbl>     <dbl>   <dbl> <int>   <dbl>  <dbl>
    ## 1     0.577         0.577  333.     2958.       0     3 -31381. 62771.
    ## # ... with 3 more variables: BIC <dbl>, deviance <dbl>, df.residual <int>

``` r
# include head circumference, length, sex, and all interactions between these
model_two_fit =
  lm(bwt ~ bhead + blength + babysex +
       (bhead * blength) + (bhead * babysex) + (blength * babysex) +
       (bhead * blength * babysex), data = birthweight_data) 

model_two_fit %>% broom::tidy()
```

    ## # A tibble: 8 x 5
    ##   term                    estimate std.error statistic      p.value
    ##   <chr>                      <dbl>     <dbl>     <dbl>        <dbl>
    ## 1 (Intercept)            -7177.     1265.       -5.67  0.0000000149
    ## 2 bhead                    182.       38.1       4.78  0.00000184  
    ## 3 blength                  102.       26.2       3.90  0.0000992   
    ## 4 babysex2                6375.     1678.        3.80  0.000147    
    ## 5 bhead:blength             -0.554     0.780    -0.710 0.478       
    ## 6 bhead:babysex2          -198.       51.1      -3.88  0.000105    
    ## 7 blength:babysex2        -124.       35.1      -3.52  0.000429    
    ## 8 bhead:blength:babysex2     3.88      1.06      3.67  0.000245

``` r
model_two_fit %>% broom::glance()
```

    ## # A tibble: 1 x 11
    ##   r.squared adj.r.squared sigma statistic p.value    df  logLik    AIC
    ## *     <dbl>         <dbl> <dbl>     <dbl>   <dbl> <int>   <dbl>  <dbl>
    ## 1     0.685         0.684  288.     1346.       0     8 -30742. 61501.
    ## # ... with 3 more variables: BIC <dbl>, deviance <dbl>, df.residual <int>

Because these are not nested models but competing models, we will compare the models using the cross-validated prediction error.

``` r
# Make this comparison in terms of the cross-validated prediction error; use crossv_mc and functions in purrr as appropriate
```
